name: ToolStats
version: '${project.version}'
main: lol.hyper.toolstats.ToolStats
api-version: 1.18
author: hyperdefined
description: Track various tool stats!
commands:
  toolstats:
    usage: /toolstats
    description: Main command.
    permission: randomenchant.reload
permissions:
  randomenchant.reload:
    description: Allows the usage of /randomenchant reload
    default: op
