name: ToolStats
version: '${project.version}'
main: lol.hyper.toolstats.ToolStats
api-version: 1.15
author: hyperdefined
description: Track various tool stats!
commands:
  toolstats:
    usage: /toolstats
    description: Main command.
    permission: toolstats.main
permissions:
  toolstats.main:
    description: Allows the usage of /toolstats
    default: true
  toolstats.reload:
    description: Allows the usage of /toolstats reload
    default: op
libraries:
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-text-minimessage:4.10.1
  - net.kyori:adventure-platform-bukkit:4.1.0